apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
  namespace: namespace-workflow-1686116725262
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: acrworkflow1686116725262.azurecr.io/image-workflow-1686116725262:latest
          ports:
            - containerPort: 8080