apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: namespace-workflow-1686116725262
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080